### PR TITLE
DNN-21313: upgrade requirejs to 2.3.5.

### LINKED ISSUE #157: Upgrade RequireJS to latest version
## Description 

Upgrade RequireJS to latest version, currently we have 2 places of requirejs referenced:

1. StructuredContentVisualizer module - version 2.3.3
2. PersonaBar - version 2.1.11

Latest version: http://requirejs.org/docs/download.html version 2.3.5
need upgrade both places to 2.3.5 and make sure nothing is broken.

### PR DESCRIPTION
**Pull request by zyhfish**
fixes #157

### CODE REVIEW

**Comment by mitchelsellers** [comment]
@zyhfish what is the impact of upgrading this library?  Are there any breaking changes that would be introduced by upgrading this library?  

@dnnsoftware/tag thoughts?

**Comment by donker** [comment]
As a general rule I prefer any dependency updates on minor, not maintenance builds. I think we *should* make an effort at keeping JS dependencies up to date as these can all of a sudden jump and leave you behind if you don't keep with the flow.

**Comment by ashishpd** [comment]
Can the community suggest a release version for this PR - will it be 9.2.1, 9.20 or 9.3.0? Can we update the milestone field for this PR?

Background - This is driven by a customer request. One of our customers has requested to upgrade this dependency as they want to take advantage of new capabilities in Require.JS. In general, there is no harm in keeping up with newer versions, provided there are no breaking changes.

@zyhfish are there any breaking changes per your analysis?

**Comment by mitchelsellers** [comment]
@ashishpd I've reviewed the release history as it relates to this extension found here: https://requirejs.org/docs/download.html#releasenotes 

It appears that there are a few changes that the developer identified as "You should not notice any negative consequences to the change, but given how important that mechanism is, it was best to rev the minor version to 2.3"

A similar note was attached to the 2.2 revision.  The intermediate revisions do not seem to pose immediate or breaking changes.

Given this, I would expect us to merge this into the 9.3.0 release.  During that release, I would also like to address the outstanding issues surrounding other references and begin a regular dependency upgrade to prevent us from being so far behind.  (For example being on 2.1.1 when the current in 2.3.5)

**Comment by ohine** [comment]
@zyhfish can you please resubmit this on the combined repository at https://github.com/dnnsoftware/Dnn.AdminExperience

**Pull request closed without merging**
